# Generated by Django 5.1.7 on 2025-04-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('scent', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
