# Generated by Django 5.1.7 on 2025-04-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
